name: dtt_real_estate
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/dtt_banner/
    - assets/images/launcher_icon.png
    - assets/images/search_state_empty.png
  fonts:
    - family: GothamSSm
      fonts:
        - asset: assets/fonts/GothamSSm/GothamSSm-Black.otf
          weight: 900
        - asset: assets/fonts/GothamSSm/GothamSSm-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GothamSSm/GothamSSm-Bold.otf
          weight: 700
        - asset: assets/fonts/GothamSSm/GothamSSm-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GothamSSm/GothamSSm-Medium.otf
          weight: 500
        - asset: assets/fonts/GothamSSm/GothamSSm-MediumItalic.otf
          weight: 500
        - asset: assets/fonts/GothamSSm/GothamSSm-Book.otf
          weight: 400
        - asset: assets/fonts/GothamSSm/GothamSSm-BookItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/GothamSSm/GothamSSm-Light.otf
          weight: 300
        - asset: assets/fonts/GothamSSm/GothamSSm-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GothamSSm/GothamSSm-XLight.otf
          weight: 200
        - asset: assets/fonts/GothamSSm/GothamSSm-XLightItalic.otf
          weight: 200
          style: italic